'use strict';
const{spawn}=require('child_process');const fs=require('fs'),http=require('http'),os=require('os'),path=require('path');const ROOT=path.resolve(__dirname,'..'),ENTRY=path.join(ROOT,'server.js'),APP_PORT=Number(process.env.PORT||3000),CONTROL_PORT=Number(process.env.CONTROL_PORT||3901),HEALTH_INTERVAL_MS=Number(process.env.HEALTH_INTERVAL_MS||15000),HEALTH_TIMEOUT_MS=Number(process.env.HEALTH_TIMEOUT_MS||3000),HEALTH_FAILURE_THRESHOLD=Number(process.env.HEALTH_FAILURE_THRESHOLD||3),RESTART_DELAY_MS=Number(process.env.RESTART_DELAY_MS||1500),TOKEN=process.env.RESTART_TOKEN||'',STATUS_FILE=process.env.MANAGER_STATUS_FILE||path.join(os.tmpdir(),'security-study-manager-status.json');let child=null,childStartedAt=null,restartCount=0,consecutiveHealthFailures=0,lastExit=null,lastRestartReason=null,plannedRestart=false,shuttingDown=false,restartTimer=null;
function log(m){console.log(`[server-manager] ${new Date().toISOString()} ${m}`)}function status(){return{managerPid:process.pid,childPid:child?.pid||null,running:Boolean(child&&child.exitCode===null&&!child.killed),appPort:APP_PORT,controlPort:CONTROL_PORT,childStartedAt,restartCount,consecutiveHealthFailures,lastRestartReason,lastExit,shuttingDown,updatedAt:new Date().toISOString()}}function persist(){try{fs.writeFileSync(STATUS_FILE,`${JSON.stringify(status(),null,2)}\n`,{mode:0o600})}catch(e){log(`status file write failed: ${e.message}`)}}
function schedule(reason,delay=RESTART_DELAY_MS){if(shuttingDown||restartTimer)return;lastRestartReason=reason;persist();restartTimer=setTimeout(()=>{restartTimer=null;start(reason)},delay)}
function start(reason='initial-start'){if(shuttingDown||child&&child.exitCode===null&&!child.killed)return;lastRestartReason=reason;consecutiveHealthFailures=0;childStartedAt=new Date().toISOString();child=spawn(process.execPath,[ENTRY],{cwd:ROOT,env:{...process.env,PORT:String(APP_PORT),MANAGER_STATUS_FILE:STATUS_FILE},stdio:'inherit',windowsHide:true});log(`application started pid=${child.pid} reason=${reason}`);persist();child.once('exit',(code,signal)=>{lastExit={at:new Date().toISOString(),code,signal};const wasPlanned=plannedRestart;plannedRestart=false;child=null;persist();if(shuttingDown){log(`application stopped during manager shutdown code=${code} signal=${signal||'-'}`);return}restartCount+=1;schedule(wasPlanned?'manual-or-health-restart':'unexpected-exit')});child.once('error',e=>{log(`failed to start application: ${e.message}`);persist()})}
function terminate(){if(!child||child.exitCode!==null||child.killed)return false;try{child.kill('SIGTERM')}catch(e){log(`SIGTERM failed: ${e.message}`);try{child.kill('SIGKILL')}catch(k){log(`SIGKILL failed: ${k.message}`)}}return true}
function restart(reason='manual-restart'){if(shuttingDown)return;lastRestartReason=reason;if(!child||child.exitCode!==null||child.killed){schedule(reason,0);return}plannedRestart=true;log(`restart requested reason=${reason}`);persist();terminate()}
function fail(reason){consecutiveHealthFailures+=1;log(`health check failed (${consecutiveHealthFailures}/${HEALTH_FAILURE_THRESHOLD}): ${reason}`);persist();if(consecutiveHealthFailures>=HEALTH_FAILURE_THRESHOLD){consecutiveHealthFailures=0;restart('health-check-failed')}}function health(){if(shuttingDown||!child)return;const r=http.get({hostname:'127.0.0.1',port:APP_PORT,path:'/api/health',timeout:HEALTH_TIMEOUT_MS},res=>{res.resume();if(res.statusCode>=200&&res.statusCode<300){if(consecutiveHealthFailures){consecutiveHealthFailures=0;persist()}return}fail(`HTTP ${res.statusCode}`)});r.on('timeout',()=>r.destroy(new Error('health check timeout')));r.on('error',e=>fail(e.message))}
function auth(req){return!TOKEN||req.headers['x-restart-token']===TOKEN}function json(res,code,payload){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(payload,null,2))}
const control=http.createServer((req,res)=>{if(!auth(req))return json(res,401,{ok:false,message:'unauthorized'});if(req.method==='GET'&&req.url==='/status')return json(res,200,{ok:true,...status()});if(req.method==='POST'&&req.url==='/restart'){restart('control-api');return json(res,202,{ok:true,message:'restart accepted',...status()})}if(req.method==='POST'&&req.url==='/start'){start('control-api-start');return json(res,202,{ok:true,message:'start accepted',...status()})}if(req.method==='POST'&&req.url==='/stop'){json(res,202,{ok:true,message:'manager shutdown accepted'});setTimeout(()=>shutdown('control-api-stop'),50);return}return json(res,404,{ok:false,message:'not found'})});
function cleanupStatus(){try{fs.unlinkSync(STATUS_FILE)}catch(_error){}}function shutdown(reason){if(shuttingDown)return;shuttingDown=true;log(`manager shutdown requested reason=${reason}`);if(restartTimer){clearTimeout(restartTimer);restartTimer=null}persist();control.close(()=>log('control server closed'));if(!terminate()){cleanupStatus();process.exit(0)}const force=setTimeout(()=>process.exit(0),5000);force.unref();const poll=setInterval(()=>{if(!child){clearInterval(poll);cleanupStatus();process.exit(0)}},100);poll.unref()}
control.listen(CONTROL_PORT,'127.0.0.1',()=>{log(`control API listening on http://127.0.0.1:${CONTROL_PORT}`);log(`runtime status file ${STATUS_FILE}`);start()});const timer=setInterval(health,HEALTH_INTERVAL_MS);timer.unref();process.on('SIGINT',()=>shutdown('SIGINT'));process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('uncaughtException',e=>{log(`uncaught exception: ${e.stack||e.message}`);shutdown('uncaughtException')});process.on('unhandledRejection',r=>log(`unhandled rejection: ${r}`));
